### ISSUE TITLE
Error en Logout

### ISSUE THREAD

**Issue by jtsoya539** [jtsoya539/proyecto-ne#2]
Al cerrar sesión se muestran caracteres extraños en el menú y otras opciones.

**Comment by DamyGenius** [comment]
vos subiste algo? me llega correos



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Javier Augusto <notifications@github.com>
Fecha: 1/11/17 15:11 (GMT-04:00)
A: jtsoya539/proyecto-ne <proyecto-ne@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [jtsoya539/proyecto-ne] Error en Logout (#2)


Al cerrar sesión se muestran caracteres extraños en el menú y otras opciones.
